### ISSUE TITLE
Impossible de charger l'extension après installation

### ISSUE THREAD

**Issue by BenoitMFr** [3liz/qgis_drain_sewer_visual_inspection#22]
ImportError: cannot import name 'postgis' from 'processing.tools' (C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins\processing\tools\__init__.py) 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/bem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drain_sewer_visual_inspection\__init__.py", line 8, in 
    from .plugin import DrainSewerVisualInspection
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/bem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drain_sewer_visual_inspection\plugin.py", line 8, in 
    from .processing_algorithms.provider import Provider
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/bem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drain_sewer_visual_inspection\processing_algorithms\provider.py", line 9, in 
    from .create_data_model_algorithm import CreateGeopackage, CreatePostgisTables
  File "C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:/Users/bem/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\drain_sewer_visual_inspection\processing_algorithms\create_data_model_algorithm.py", line 9, in 
    from processing.tools import postgis
ImportError: cannot import name 'postgis' from 'processing.tools' (C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins\processing\tools\__init__.py)

**Comment by BenoitMFr** [comment]
![Capture](https://user-images.githubusercontent.com/50232731/121690537-41ba5d00-cac6-11eb-8f27-7c953421db88.JPG)

**Comment by Gustry** [comment]
En effet, l'extension n'est pas compatible QGIS >= 3.16 (et même >= 3.14 je pense)

**Comment by pasqal** [comment]
Allez-vous rendre l'extension compatible avec QGIS >3.16 ? Sinon, connaissez-vous les raisons de l'incompatibilité et quels sont les parties de code à changer. Merci

**Comment by ValentinRavier** [comment]
Bonjour,

Est ce que des évolutions sont prévues sur le plug-in pour le rendre compatible avec les dernières versions de QGIS ?

Merci

**Comment by Gustry** [comment]
> Sinon, connaissez-vous les raisons de l'incompatibilité et quels sont les parties de code à changer.

Selon la capture d'écran ci-dessus, il s'agit de l'API de QGIS.
Pas mal de code a été supprimé entre QGIS 3.10 et QGIS 3.16 pour dialoguer avec une base de données. Il y a désormais une nouvelle API stable qu'il faut utiliser et ce code ne changera plus avant QGIS 4 au moins (si il change).

Pour le moment, nous n'avons pas d'évolutions de notre côté, n'hésitez pas à nous contacter.

**Comment by pasqal** [comment]
Merci pour la réponse. Je ai déjà contacté pour proposer de financer l'évolution. Malheureusement, jamais eu de réponse.

**Comment by ValentinRavier** [comment]
@pasqal : tu peux contacter 3liz (l'entreprise de Gustry) pour une demande d'évolution sur info@3liz.com, ils te fourniront un devis

**Comment by pasqal** [comment]
@ValentinRavier C'est bien ce que j'ai déjà fait :(
